/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestSanduAdrian;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.codeborne.selenide.Configuration;

import common.Format;
import common.NavigateToObject;
import defaultvalues.NavigateTo;
import defaultvalues.SetDataForTest;
import ghost.pagesteps.CommunityForumPageSteps;
import ghost.pagesteps.ResultPageSteps;
import way2automation.pages.PopUpDataModel;
import way2automation.pagesteps.DashboardPageSteps;
import way2automation.pagesteps.DatePickerSteps;
import way2automation.pagesteps.PopUpWindowPageSteps;

public class LibraryTest
{
	//Objects used in both tests.
	NavigateToObject navigateToObject = new NavigateToObject();

	PopUpWindowPageSteps popUpWindowPageSteps = new PopUpWindowPageSteps();

	PopUpDataModel popUpDataModel = new PopUpDataModel();

	CommunityForumPageSteps communityForumPageSteps = new CommunityForumPageSteps();

	ResultPageSteps resultPageSteps = new ResultPageSteps();

	SetDataForTest setDataForTest = new SetDataForTest();

	DashboardPageSteps dashboardPageSteps = new DashboardPageSteps();

	DatePickerSteps datePickerSteps = new DatePickerSteps();

	@BeforeEach
	public void beforeEach()
	{
		//Set timeout value
		Configuration.timeout = 10000;
	}

	@Test
	/*
	 TestNumberOne:
	 a. Navigate to https://ghost.org/
	 b. Navigate to "Community Forum" section using the "Resources" menu.
	 c. Search for “create new blog”
	 d. Open one of the search results
	*/
	void testNumberOne()
	{
		String searchValue = "create new blog";
		//Step a.
		navigateToObject.navigateTo(NavigateTo.GHOSTLINK);
		//Step b
		navigateToObject.navigateTo(NavigateTo.COMMUNITY_FORUM);
		//Step c
		communityForumPageSteps.searchFor(searchValue);
		//Step d
		communityForumPageSteps.openRandomResult();
		//Check that Step d is executed with success.
		assertTrue(resultPageSteps.isValidResult(searchValue));
	}

	/*
	 TestNumberTwo:
	a. Navigate to http://way2automation.com/way2auto_jquery/index.php  
	b. Fill in the mandatory info and submit the form (pop-up registration form appears with no cookies from the page on first visit).
	c. Open the "Date picker" widget.
	d. Navigate to the "FORMAT DATE" section.
	e. Select today's date.
	f. Select the "ISO 8601" Format option.
	g. Validate the shown date against the current date.
	*/
	@Test
	void testNumberTwo()
	{
		//Object that contains data used in test execution.
		popUpDataModel = setDataForTest.getPopUpDataModel();
		//Step a.
		navigateToObject.navigateTo(NavigateTo.WAY_TWO_LINK);
		//Step b
		popUpWindowPageSteps.submitData(popUpDataModel);
		//Step c
		dashboardPageSteps.openDatePicker();
		//Step d
		datePickerSteps.clickOnFormatDateTab();
		//Step e
		datePickerSteps.selectTodayDateFormatDate();
		//Check Step e is executed with success.
		assertTrue(datePickerSteps.isCorrectFormat(Format.DEFAULT));
		//Step f
		datePickerSteps.selectFormatOptions(Format.ISO8601.getValue());
		//Step g
		assertTrue(datePickerSteps.isCorrectFormat(Format.ISO8601));
	}
}
